//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3603
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicLand.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:LyricWiki", ConfigurationName="ServiceReference1.LyricWikiPortType")]
    public interface LyricWikiPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LyricWiki#checkSongExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool checkSongExists(string artist, string song);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LyricWiki#searchArtists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string[] searchArtists(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LyricWiki#searchAlbums", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string[] searchAlbums(string artist, string album, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LyricWiki#searchSongs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MusicLand.ServiceReference1.SongResult searchSongs(string artist, string song);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LyricWiki#getSOTD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MusicLand.ServiceReference1.SOTDResult getSOTD();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LyricWiki#getSong", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MusicLand.ServiceReference1.LyricsResult getSong(string artist, string song);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LyricWiki#getSongResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="songResult")]
        MusicLand.ServiceReference1.LyricsResult getSongResult(string artist, string song);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LyricWiki#getArtist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void getArtist(ref string artist, out string[] albums);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LyricWiki#getAlbum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void getAlbum(ref string artist, ref string album, ref int year, out string amazonLink, out string[] songs);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LyricWiki#getHometown", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="country")]
        string getHometown(out string state, out string hometown, string artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LyricWiki#postArtist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void postArtist(bool overwriteIfExists, ref string artist, out bool dataUsed, out string message, string[] albums);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LyricWiki#postAlbum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void postAlbum(bool overwriteIfExists, ref string artist, ref string album, ref int year, out bool dataUsed, out string message, string asin, string[] songs);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LyricWiki#postSong", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void postSong(bool overwriteIfExists, ref string artist, ref string song, out bool dataUsed, out string message, string lyrics, string[] onAlbums);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LyricWiki#postSong_flags", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void postSong_flags(bool overwriteIfExists, ref string artist, ref string song, out bool dataUsed, out string message, string lyrics, string[] onAlbums, string flags);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:LyricWiki")]
    public partial class SongResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string artistField;
        
        private string songField;
        
        /// <comentarios/>
        public string artist {
            get {
                return this.artistField;
            }
            set {
                this.artistField = value;
                this.RaisePropertyChanged("artist");
            }
        }
        
        /// <comentarios/>
        public string song {
            get {
                return this.songField;
            }
            set {
                this.songField = value;
                this.RaisePropertyChanged("song");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:LyricWiki")]
    public partial class LyricsResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string artistField;
        
        private string songField;
        
        private string lyricsField;
        
        private string urlField;
        
        /// <comentarios/>
        public string artist {
            get {
                return this.artistField;
            }
            set {
                this.artistField = value;
                this.RaisePropertyChanged("artist");
            }
        }
        
        /// <comentarios/>
        public string song {
            get {
                return this.songField;
            }
            set {
                this.songField = value;
                this.RaisePropertyChanged("song");
            }
        }
        
        /// <comentarios/>
        public string lyrics {
            get {
                return this.lyricsField;
            }
            set {
                this.lyricsField = value;
                this.RaisePropertyChanged("lyrics");
            }
        }
        
        /// <comentarios/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:LyricWiki")]
    public partial class SOTDResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string artistField;
        
        private string songField;
        
        private string nominatedByField;
        
        private string reasonField;
        
        private string lyricsField;
        
        /// <comentarios/>
        public string artist {
            get {
                return this.artistField;
            }
            set {
                this.artistField = value;
                this.RaisePropertyChanged("artist");
            }
        }
        
        /// <comentarios/>
        public string song {
            get {
                return this.songField;
            }
            set {
                this.songField = value;
                this.RaisePropertyChanged("song");
            }
        }
        
        /// <comentarios/>
        public string nominatedBy {
            get {
                return this.nominatedByField;
            }
            set {
                this.nominatedByField = value;
                this.RaisePropertyChanged("nominatedBy");
            }
        }
        
        /// <comentarios/>
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <comentarios/>
        public string lyrics {
            get {
                return this.lyricsField;
            }
            set {
                this.lyricsField = value;
                this.RaisePropertyChanged("lyrics");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface LyricWikiPortTypeChannel : MusicLand.ServiceReference1.LyricWikiPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LyricWikiPortTypeClient : System.ServiceModel.ClientBase<MusicLand.ServiceReference1.LyricWikiPortType>, MusicLand.ServiceReference1.LyricWikiPortType {
        
        public LyricWikiPortTypeClient() {
        }
        
        public LyricWikiPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LyricWikiPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LyricWikiPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LyricWikiPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool checkSongExists(string artist, string song) {
            return base.Channel.checkSongExists(artist, song);
        }
        
        public string[] searchArtists(string searchString) {
            return base.Channel.searchArtists(searchString);
        }
        
        public string[] searchAlbums(string artist, string album, int year) {
            return base.Channel.searchAlbums(artist, album, year);
        }
        
        public MusicLand.ServiceReference1.SongResult searchSongs(string artist, string song) {
            return base.Channel.searchSongs(artist, song);
        }
        
        public MusicLand.ServiceReference1.SOTDResult getSOTD() {
            return base.Channel.getSOTD();
        }
        
        public MusicLand.ServiceReference1.LyricsResult getSong(string artist, string song) {
            return base.Channel.getSong(artist, song);
        }
        
        public MusicLand.ServiceReference1.LyricsResult getSongResult(string artist, string song) {
            return base.Channel.getSongResult(artist, song);
        }
        
        public void getArtist(ref string artist, out string[] albums) {
            base.Channel.getArtist(ref artist, out albums);
        }
        
        public void getAlbum(ref string artist, ref string album, ref int year, out string amazonLink, out string[] songs) {
            base.Channel.getAlbum(ref artist, ref album, ref year, out amazonLink, out songs);
        }
        
        public string getHometown(out string state, out string hometown, string artist) {
            return base.Channel.getHometown(out state, out hometown, artist);
        }
        
        public void postArtist(bool overwriteIfExists, ref string artist, out bool dataUsed, out string message, string[] albums) {
            base.Channel.postArtist(overwriteIfExists, ref artist, out dataUsed, out message, albums);
        }
        
        public void postAlbum(bool overwriteIfExists, ref string artist, ref string album, ref int year, out bool dataUsed, out string message, string asin, string[] songs) {
            base.Channel.postAlbum(overwriteIfExists, ref artist, ref album, ref year, out dataUsed, out message, asin, songs);
        }
        
        public void postSong(bool overwriteIfExists, ref string artist, ref string song, out bool dataUsed, out string message, string lyrics, string[] onAlbums) {
            base.Channel.postSong(overwriteIfExists, ref artist, ref song, out dataUsed, out message, lyrics, onAlbums);
        }
        
        public void postSong_flags(bool overwriteIfExists, ref string artist, ref string song, out bool dataUsed, out string message, string lyrics, string[] onAlbums, string flags) {
            base.Channel.postSong_flags(overwriteIfExists, ref artist, ref song, out dataUsed, out message, lyrics, onAlbums, flags);
        }
    }
}
